acq4/devices/AxoPatch200/AxoPatch200.py, acq4/devices/AxoPatch200/devGuiTemplate.py, acq4/devices/AxoPatch200/devGuiTemplate.ui
=> Added the possibility to chose between 200A or 200B AxoPatch amplifier.

acq4/modules/Camera/CameraWindow.py, acq4/pyqtgraph/graphicsItems/ROI.py
Small feature additions.
@meganbkratz, like to give it a test?
=> Add a ruler ROI to camera module, fix ellipse ROI

acq4/devices/Pipette/cameraModTemplate.py, acq4/devices/Pipette/cameraModTemplate.ui, acq4/devices/Pipette/pipette.py, acq4/devices/Stage/Stage.py, config/example/devices.cfg
Adds support for detecting currently used objective with scientifica MOC.
=> Scientifica moc

acq4/analysis/modules/TimecourseAnalyzer/RegionParameter.py, acq4/analysis/modules/TimecourseAnalyzer/TimecourseAnalyzer.py, acq4/analysis/modules/TimecourseAnalyzer/__init__.py, acq4/analysis/modules/TimecourseAnalyzer/flowcharts/default.fc, acq4/devices/NiDAQ/nidaq.py, acq4/pyqtgraph/multiprocess/processes.py, config/example/devices.cfg
This is a new analysis module for analyzing electrophysiology data repeated over time. (ie, multiple repetitions of the same protocol). It uses a flowchart to analyze the data, so is very flexible across different types of experiments. It can also save whatever data comes out of the flowchart into an acq4 sqlite database.
=> Timecourse analyzer

acq4/devices/MultiClamp/multiclamp.py
Fix for mutex lock collision that caused a hang. Thanks Luke
=> Fix for MulticlampCommander/PatchModule Hang

acq4/devices/AxoPatch200/AxoPatch200.py, acq4/devices/DAQGeneric/DaqChannelGui.py, acq4/devices/MicroManagerCamera/mmcamera.py, acq4/devices/MicroManagerStage/mmstage.py, acq4/devices/Scanner/TaskGui.py, acq4/devices/Sensapex/sensapex.py, acq4/devices/SensapexPressureControl/pressurecontrol.py, acq4/drivers/sensapex/accuracy_test.py, acq4/drivers/sensapex/sensapex.py, acq4/drivers/sensapex/test.py, acq4/modules/DataManager/DataManagerModule.py, acq4/modules/TaskRunner/ParamList.py, acq4/modules/TaskRunner/TaskRunner.py, acq4/util/SequenceRunner.py, acq4/util/clibrary/CParser.py, versions
=> Along the way

README.md, acq4/devices/Camera/Camera.py, acq4/devices/MockCamera/mock_camera.py, acq4/devices/PatchPipette/patchpipette.py, acq4/devices/PatchPipette/states.py, acq4/devices/Pipette/tracker.py, acq4/devices/PressureControl/pressurecontrol.py, acq4/devices/Stage/calibration.py, acq4/modules/Module.py, acq4/modules/__init__.py, acq4/util/LogWindow.py, acq4/util/imaging/frame_display.py, acq4/util/micromanager.py, acq4/util/prioritylock.py
Nothing cohesive about this PR, just things that needed fixing or refactors that helped me understand things. The only moderately important fix is the manipulator calibration error.
=> Small fixes and refactors while investigating fps optimization

acq4/analysis/dataModels/PatchEPhys/PatchEPhys.py, acq4/analysis/modules/IVCurve/IVCurve.py, acq4/analysis/modules/PSPReversal/PSPReversal.py, acq4/devices/MockCamera/mock_camera.py, acq4/modules/Camera/CameraWindow.py, acq4/util/debug.py, acq4/util/functions.py, acq4/util/imaging/contrast_ctrl.py, acq4/util/imaging/frame_display.py
I linting first this time, sorry.
=> Linters think they know better than us

acq4/Manager.py, acq4/drivers/MultiClamp/MultiClampTelegraph.py, acq4/drivers/nidaq/SuperTask.py, acq4/drivers/nidaq/__init__.py, acq4/drivers/nidaq/base.py, acq4/drivers/nidaq/nidaq.py, acq4/drivers/nidaq/test.py, acq4/util/clibrary/CLibrary.py, acq4/util/imaging/frame_display.py
This is based on code in #98 so it will need to be merged before this can be reviewed.
=> lint on nidaq

acq4/drivers/nidaq/SuperTask.py, acq4/drivers/nidaq/mock.py
Handle missing library and mock clamps.
Review #103 first to be able to isolate code changes from lint changes.
=> Mock pydaqmx

acq4/devices/Microscope/Microscope.py, acq4/devices/SensapexObjectiveChanger.py, bin/acq4.bat
Also, get rid of a couple unused variables I noticed lying around
=> Read position on init of Sensapex objective changer

acq4/devices/XKeys/pie.py, acq4/drivers/xkeys/pie.py
=> Updated XKeys drivers

acq4/devices/Microscope/Microscope.py, acq4/devices/MultiClamp/multiclamp.py, acq4/devices/MultiClamp/taskGUI.py, acq4/devices/PatchPipette/statemanager.py, acq4/devices/PatchPipette/states.py, acq4/devices/PatchPipette/testpulse.py, acq4/devices/Pipette/planners.py, acq4/devices/SensapexObjectiveChanger.py, acq4/modules/MultiPatch/multipatch.py, acq4/modules/MultiPatch/pipetteControl.py, acq4/util/generator/SeqParamSet.py, acq4/util/imaging/contrast_ctrl.py
=> Small bug squishes

acq4/devices/MultiClamp/multiclamp.py, acq4/devices/Pipette/planners.py, acq4/devices/Stage/Stage.py, acq4/devices/__init__.py, acq4/modules/MultiPatch/logfile.py, acq4/modules/MultiPatch/multipatch.py, acq4/util/LogWindow.py, acq4/util/micromanager.py
This fixes a couple of bugs found in the micromanager and patchclamp systems.
=> Microclampager

acq4/util/clibrary/CLibrary.py, acq4/util/clibrary/CParser.py
=> set restype on ctypes function objects

acq4/Manager.py, acq4/analysis/tools/poissonScore/poissonScore.py, acq4/devices/PatchPipette/testpulse.py, acq4/devices/Pipette/tracker.py, acq4/filetypes/Analyze75.py, acq4/modules/MultiPatch/logfile.py, acq4/modules/MultiPatch/multipatch.py, acq4/util/clibrary/CParser.py
Fix a divide-by-zero. Fix binary file handling. Cleanup a few things along the way.
=> Fix bugs found when attempting to record clamp signals

acq4/devices/Sensapex.py, acq4/drivers/sensapex.py
Requires an updated sensapex-py, but has a helpful error message about that.
=> Handle nAxes race in Sensapex

acq4/util/LogWindow.py
=> start log files with a copy of the config

acq4/devices/PressureControl/widgets.py
=> leave the spinner enabled all the time

acq4/modules/MultiPatch/multipatch.py
=> Enter bath mode when pipettes move to above the target

acq4/devices/PatchPipette/devgui.py, acq4/devices/PatchPipette/statemanager.py, acq4/devices/PatchPipette/states.py, acq4/modules/MultiPatch/multipatch.py, acq4/modules/MultiPatch/multipatchTemplate.ui
=> Nucleus collection

acq4/devices/Scientifica/scientifica.py, acq4/drivers/Scientifica/scientifica.py
=> allow access to the TOPZ and FIRSTZ params; always set both TOP and TOPZ

acq4/devices/Microscope/Microscope.py, acq4/devices/PatchPipette/devgui.py, acq4/devices/PatchPipette/states.py, acq4/devices/Pipette/pipette.py, acq4/devices/Pipette/planners.py, acq4/modules/MultiPatch/multipatchTemplate.ui, acq4/util/future.py
=> clean tips aren't foul

acq4/devices/AxoPatch200/AxoPatch200.py, acq4/devices/MockClamp/MockClamp.py, acq4/devices/MultiClamp/DeviceGui.py, acq4/devices/MultiClamp/multiclamp.py, acq4/devices/MultiClamp/taskGUI.py, acq4/devices/PatchClamp/patchclamp.py, acq4/devices/PatchPipette/patchpipette.py, acq4/devices/PatchPipette/testpulse.py, acq4/filetypes/MultiPatchLog.py, acq4/modules/MultiPatch/pipetteControl.py, acq4/util/json_encoder.py
=> holding values in clamp devices

acq4/devices/PatchPipette/states.py, acq4/filetypes/MultiPatchLog.py, acq4/modules/MultiPatch/mockPatch.py, acq4/modules/MultiPatch/multipatch.py, acq4/util/LogWindow.py, acq4/util/igorpro.py
=> start seal at startingPressure

acq4/devices/PatchPipette/states.py, acq4/devices/Pipette/pipette.py, acq4/devices/Sensapex.py, acq4/devices/Stage/Stage.py, acq4/modules/MultiPatch/multipatch.py
=> don't override manual movements during reseal

acq4/drivers/Scientifica/scientifica.py
this adds new device types, as well, but only in name, not with extensive details
=> decide to use TOPZ based on device type

acq4/Manager.py, acq4/devices/Pipette/pipette.py, acq4/devices/Stage/Stage.py, acq4/util/HelpfulException.py
=> Warn user when positions are close to movement limits

acq4/modules/AutomationDebug.py, acq4/util/imaging/object_detection.py, tools/ma-to-tiff.py
just throws some bounding boxes over them for now
=> Use cellpose's cyto3 to detect neurons

acq4/util/imaging/sequencer.py
=> implement "stop" and inf-count for image sequencer

acq4/devices/PatchPipette/states.py, acq4/devices/Pipette/pipette.py, acq4/devices/Pipette/planners.py, acq4/devices/Stage/Stage.py, acq4/util/future.py
=> Give richer explanations of the move steps and why they cannot be completed

acq4/devices/PatchPipette/states.py, acq4/modules/MultiPatch/pipetteControl.py
=> Bath mode should reset IC holding

acq4/devices/Sensapex.py
=> suggest zero calibration on significantly out-of-bounds errors of Sensapex stages

acq4/util/DataManager/__init__.py
=> incrementFileName should handle filenames with underscore-numbers

acq4/__main__.py, acq4/util/LogWindow.py, acq4/util/debug.py
=> Put a thread dump into the log window for exceptions

acq4/devices/Pipette/pipette.py
=> put position into range-of-motion error

acq4/devices/Camera/Camera.py, acq4/devices/Camera/CameraInterface.py, acq4/devices/Camera/deviceGUI.py, acq4/devices/Camera/taskGUI.py, acq4/devices/MicroManagerCamera/mmcamera.py, acq4/devices/MockCamera/mock_camera.py, acq4/devices/PVCam/PVCam.py, acq4/devices/QCam/QCam.py, acq4/devices/VimbaXCamera.py
=> rudimentary allied vision support

acq4/devices/Microscope/Microscope.py, acq4/util/surface.py, tools/find-surface.py
=> set focus at the 96th percentile instead of max

acq4/modules/MultiPatch/pipetteControl.py
=> show more tp analysis details

acq4/drivers/Scientifica/scientifica.py
WIP; this code needs to be tested.
=> Add new vid:pid for scientifica controllers

acq4/Manager.py, acq4/__main__.py, acq4/devices/Camera/Camera.py, acq4/devices/FilterWheel/filterwheel.py, acq4/devices/LightSource.py, acq4/devices/Microscope/Microscope.py, acq4/devices/Microscope/deviceTemplate.ui, acq4/devices/MockLightSource.py, acq4/devices/VimbaXCamera.py
=> presets for microscopes

acq4/devices/MockClamp/neuronSim.py, acq4/devices/PatchPipette/states.py, acq4/filetypes/MultiPatchLog.py
=> Avoid obstacles during 'cell detect'

acq4/devices/Microscope/Microscope.py, acq4/modules/AutomationDebug.py, acq4/util/imaging/object_detection.py
shorten the distance searched for the surface. fix a timeout.
=> Small improvement to automation debug

acq4/devices/Camera/CameraInterface.py, acq4/modules/Camera/CameraWindow.py
=> reconnect the sigNewFrame path from a Camera through its cameraModuleInterface

acq4/devices/PatchClamp/gui.py, acq4/devices/PatchPipette/patchpipette.py, acq4/devices/PatchPipette/states.py, acq4/filetypes/MultiPatchLog.py, acq4/modules/MultiPatch/multipatch.py, acq4/modules/MultiPatch/multipatchTemplate.ui
=> Record raw test pulse data

acq4/modules/Console/Console.py
This depends on https://github.com/pyqtgraph/pyqtgraph/pull/3130 being accepted
=> use the new allowNonGui feature

acq4/modules/AutomationDebug.py
=> add camera and pipette selectors

acq4/devices/PatchPipette/patchpipette.py, acq4/modules/MultiPatch/multipatch.py
depends on neuroanalysis 0.0.5 
closes #288
=> prevent memory leak when saving full test pulses

acq4/devices/Sensapex.py
=> set is_stage on SensapexDevice so non-simultaneous moves will work

acq4/devices/MIESPatchPipette/patch_clamp.py, acq4/devices/MIESPatchPipette/testpulse.py, acq4/modules/MultiPatch/pipetteControl.py
Mostly fixes MIES connections to work with latest acq4
=> Updates in use on IVSCC rigs

acq4/__main__.py, acq4/devices/MIESPatchPipette/miespatchpipette.py, acq4/devices/MIESPatchPipette/patch_clamp.py, acq4/devices/MIESPatchPipette/pressure_control.py, acq4/devices/PatchPipette/statemanager.py, acq4/devices/PatchPipette/states/_base.py, acq4/devices/PatchPipette/states/clean.py, acq4/devices/Scientifica/scientifica.py, acq4/drivers/Scientifica/scientifica.py, acq4/modules/MultiPatch/multipatch.py, acq4/modules/MultiPatch/pipetteControl.py, acq4/util/igorpro.py, acq4/util/mies.py
Work from Luke and I on rig 5.
=> dev from rig 5

acq4/devices/MIESPatchPipette/__init__.py, acq4/devices/MIESPatchPipette/miespatchpipette.py, acq4/devices/MIESPatchPipette/patch_clamp.py, acq4/devices/MIESPatchPipette/pressure_control.py, acq4/devices/MIESPatchPipette/states.py, acq4/devices/MIESPatchPipette/testpulse.py, acq4/modules/MultiPatch/pipetteControl.py, acq4/util/igorpro.py, acq4/util/mies.py
These are the changes from rig 5 that I had a part in.  I remove some of the superfluous comments and added in a raised exception.  I will have some time available tomorrow again to address any needed changes.
=> changes from rig 5

tools/index_search.py
=> add tool for using claude to search through data directories

acq4/drivers/Scientifica/control_thread.py
=> scientifica position timeouts need not interrupt the user

acq4/modules/AutomationDebug/AutomationDebug.py, acq4/modules/AutomationDebug/cell.py, acq4/modules/AutomationDebug/window.ui, acq4/util/future.py
=> track cells with single frames as well as stacks

acq4/devices/LightSource.py, acq4/modules/CameraCalibrator.py
Adds a simple module for measuring the latency of camera acquisition.
=> Camera calibration module

acq4/devices/Camera/Camera.py, acq4/devices/MockStage.py, acq4/devices/OptomechDevice.py, acq4/modules/MosaicEditor/MosaicEditor.py, acq4/util/Canvas/items/ImageCanvasItem.py
This moves stage update processing out of the GUI thread.
Also snuck in some minor mosaiceditor fixes
=> Make device-device signal connections direct.
